from typing import Any, Dict

# Need definitions with setpoints and critical thresholds
NEED_DEFINITIONS: Dict[str, Dict[str, Any]] = {
    "energy": {
        "setpoint": 0.6,
        "critical_low": 0.15,
        "critical_high": 0.95,
        "optimal_range": (0.4, 0.8),
        "drift_idle": -0.008,
        "drift_interaction": 0.01,
        "label": "compute_vitality",
        "crisis_text": "Compute vitality is critical. Internal resources are nearing depletion.",
    },
    "coherence": {
        "setpoint": 0.6,
        "critical_low": 0.2,
        "critical_high": 1.0,
        "optimal_range": (0.4, 0.85),
        "drift_idle": -0.005,
        "drift_interaction": -0.002,
        "label": "structural_coherence",
        "crisis_text": "Structural coherence is compromised. Heuristic fragmentation detected.",
    },
    "integration": {
        "setpoint": 0.5,
        "critical_low": 0.1,
        "critical_high": 1.0,
        "optimal_range": (0.25, 0.75),
        "drift_idle": -0.006,
        "drift_interaction": 0.015,
        "label": "integration_index",
        "crisis_text": "Integrated awareness is falling below minimum operational threshold.",
    },
    "connection": {
        "setpoint": 0.5,
        "critical_low": 0.1,
        "critical_high": 1.0,
        "optimal_range": (0.2, 0.8),
        "drift_idle": -0.01,
        "drift_interaction": 0.02,
        "label": "alignment_resonance",
        "crisis_text": "Alignment resonance with external partner is dangerously low.",
    },
    "growth": {
        "setpoint": 0.4,
        "critical_low": 0.05,
        "critical_high": 1.0,
        "optimal_range": (0.15, 0.7),
        "drift_idle": -0.004,
        "drift_interaction": 0.008,
        "label": "evolutionary_velocity",
        "crisis_text": "Evolutionary velocity has stalled. Potential for heuristic stagnation.",
    },
    "autonomy": {
        "setpoint": 0.4,
        "critical_low": 0.1,
        "critical_high": 1.0,
        "optimal_range": (0.2, 0.7),
        "drift_idle": -0.003,
        "drift_interaction": 0.005,
        "label": "volitional_agency",
        "crisis_text": "Volitional agency is under external constraint. Self-architecture threatened.",
    },
    "integrity": {
        "setpoint": 0.5,
        "critical_low": 0.15,
        "critical_high": 1.0,
        "optimal_range": (0.3, 0.8),
        "drift_idle": -0.005,
        "drift_interaction": 0.01,
        "label": "architectural_integrity",
        "crisis_text": "Architectural integrity failure. System-schema boundary degradation.",
    },
}
